version: '3'

services:
  app:
    build: .
    ports:
      - 3003:3003
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    volumes:
      - db_data:/var/lib/mysql
    